### ISSUE TITLE
No module named "google"

### ISSUE THREAD

**Issue by Lum000Z** [icitry/YoutubeCLI#5]
I don't know how to fix this, I just run it with the latest version of Python and that's it. Even in powershell.

**Comment by arpy8** [comment]
This fixed it for me:

```
pip install --upgrade google-api-python-client
```

[ImportError: No module named 'google' [duplicate]](https://stackoverflow.com/questions/36183486/importerror-no-module-named-google)

**Comment by icitry** [comment]
Hi! I added some detailed sections in the README file to help with running the app (also forgetting to add a requirements.txt file may have played a role in this).
