### ISSUE TITLE
IndexError raised on navigating to search page

### ISSUE THREAD

**Issue by approachcircle** [icitry/YoutubeCLI#7]
when entering the search page from the home page, this error is raised:

![image](https://github.com/icitry/YoutubeCLI/assets/58401347/3f85e76d-847f-4377-bc6f-bbdf8f06e0d6)

not sure why, I thought strings could be indexed reversely if a negative index is provided but it fails here

(I'm also on the newest version of python)

**Comment by icitry** [comment]
Should be fixed with the latest version.
