### ISSUE TITLE
shifted frames on playing

### ISSUE THREAD

**Issue by ferrovovan** [icitry/YoutubeCLI#9]
System: Ubuntu 22.04 LTS

When the video is paused, frames are displayed correctly. However, during playback, symbols shift across the entire width of the terminal.
Wrong (on playing):
![bug](https://github.com/icitry/YoutubeCLI/assets/143318281/b4bf11af-f415-4ce8-adbc-641b9ededfbd)
Correct (on pause):
![correct](https://github.com/icitry/YoutubeCLI/assets/143318281/7d6654b5-5523-457c-a137-43dbe672637a)
params: --max-width 60 --colors

**Comment by icitry** [comment]
Should be fixed now with the latest commit.
